# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  - main

pool:
  name: az_agent

jobs:
  - job: SetupPython
    displayName: 'Run tests with Python 3.13 on Windows'
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            python --version
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        displayName: 'Install dependencies'
        
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            pip install pytest pytest-azurepipelines
            pytest
        displayName: 'Run pytest'

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "Tests completed!"
        displayName: 'Post-test message'
